### ISSUE TITLE
Image path for single objects benchmark

### ISSUE THREAD

**Issue by vishwa27yvs** [arijitray1993/COLA#3]
The `COLA_singleobjects_benchmark_GQA.json` includes path to images, but I am not sure what these IDs refer to, example: `/projectnb/ivc-ml/array/data/VisualGenome/images/2343566.jpg`, is 2343566 the visual genome id? how should I download these images?

**Comment by arijitray1993** [comment]
Yes, you are correct, they are the GQA (subset of Visual Genome) image IDs. You should be able to get the images from here: https://cs.stanford.edu/people/dorarad/gqa/download.html.
